[workspace]
members = ["hsnap", "hsnap-purl-plugin"]
resolver = "2"

[build]
target = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"