[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

# Optional: Configuration for using 'cross' if you use it
[net]
git-fetch-with-cli = true
